#!/bin/bash

source common-lib

ARGS=$@

build_password() {
	local user=$1
	local domain=$2
	local key=$3
	local algorithm=$4
	local delimeter=$5
	echo -n "$user$delimeter$domain$delimeter$key" | $algorithm | tr -d "-"
}

get_password_for_domain() {
	local user=$(get_user)
	local domain=$1
	local key=$(get_master_key)
	local algorithm=$(get_hash_algorithm)
	local delimeter=$(get_delimeter)
	local password=$(build_password $user $domain $key $algorithm $delimeter)

	echo $password
}

main() {
	run_only_in_super_user_mode $BASH_SOURCE $ARGS
	import "secret-config"

	domain=$1
	if [ -z $domain ]; then 
		echo "domain is empty"
	else
		echo "$domain:"
	fi

	password=$(get_password_for_domain $domain)

	echo $password 
	echo $password | xclip
}

main $1
