#!/bin/bash

volume_up() {
	amixer set Master 500+ unmute
}

volume_down() {
	amixer set Master 500- unmute
}

toggle_mute_unmute() {
	amixer set Master toggle
}

mute() {
	amixer set Master mute
}

unmute() {
	amixer set Master unmute
}

main() {
	command=$1
	case "$command" in
	("+") volume_up ;;
	("-") volume_down ;;
	("0") toggle_mute_unmute;;
esac
}

main $@
